project_id = "wcdyxxthaqzchjpharwh"

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-register]
verify_jwt = false

[functions.whatsapp-request-code]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = false

[functions.whatsapp-debug]
verify_jwt = false

[functions.media-proxy]
verify_jwt = false

[functions.toggle-user-status]
verify_jwt = true
